### PR TITLE
0.16.1 bug fixes: IR staleness checksum (#1012), restore testing helpers (#1011)

### LINKED ISSUE #1011: `assert_invalid`/`assert_valid` removed from `protean.testing` without a CHANGELOG entry
## Summary

`assert_valid` and `assert_invalid` were removed from `protean.testing` in 0.16.0 (commit "Remove assert_valid and assert_invalid from testing DSL"), but the 0.16.0 CHANGELOG has **no `### Removed` section** and no mention of the removal. The rationale and migration live only in the commit message. Downstream test suites that import these helpers break at collection time on upgrade with no changelog breadcrumb.

## Environment

- Protean 0.16.0

## Reproduction

```python
from protean.testing import assert_invalid
# ImportError: cannot import name 'assert_invalid' from 'protean.testing'
```

## Expected vs actual

- **Expected:** removal of a public, documented testing helper is announced in the CHANGELOG with a migration note (Keep a Changelog `### Removed`).
- **Actual:** no changelog entry; downstream suites discover it as an `ImportError`.

## Proposed fix

- Backfill a `### Removed` entry into the 0.16.0 CHANGELOG with the migration: replace `assert_invalid(lambda: op(), message="X")` with `with pytest.raises(ValidationError, match="X"): op()`; `assert_valid(lambda: op())` becomes a plain `op()`.
- Consider a deprecation cycle for testing-DSL helpers (warn in one minor, remove in the next), since they appear in every downstream test suite. (Related: #999 reusable deprecation mechanism.)

Found via ShopStream: 25 call sites across 8 test files broke on upgrade.

### LINKED ISSUE #1012: `ir check` reports stale when `ir diff` reports no changes (timestamp-only difference)
## Summary

After upgrading a project from 0.15 to 0.16, `protean ir check` reports every domain as **stale**, while `protean ir diff` reports **"No changes detected"** for the same domains. Regenerating the baselines produces a one-line diff per file — only the `generated_at` timestamp changes. The two commands disagree, and the staleness signal fires with no real domain change.

## Environment

- Protean 0.16.0 (upgrading from 0.15.x baselines)

## Reproduction

1. Materialize IR baselines under 0.15 (`protean ir show > .protean/<domain>/ir.json`).
2. Upgrade to 0.16.0.
3. `protean ir check --domain <d> --dir .protean/<d>` → "IR is stale — domain has changed since last materialization."
4. `protean ir diff --domain <d> --dir .protean/<d>` → "No changes detected."
5. Regenerate: the only change in `ir.json` is the `generated_at` field.

## Expected vs actual

- **Expected:** `ir check` and `ir diff` agree; staleness reflects a real content change.
- **Actual:** `ir check` flags stale on a timestamp/version-only difference that `ir diff` ignores.

## Proposed fix

Base the staleness checksum on IR **content**, excluding volatile metadata (`generated_at`, framework version). Alternatively, have `ir check` report *why* it is stale (content vs. metadata/version) so an upgrade-triggered, content-free staleness is distinguishable from a real drift.

Found via ShopStream while refreshing IR baselines after the 0.16.0 upgrade.

### PR DESCRIPTION
**Pull request by subhashb**
Two upgrade-path bugs surfaced by a downstream app (ShopStream) on the 0.16.0 upgrade, both targeted for the **0.16.1** patch.

## #1012 — `ir check` falsely reports stale after a framework upgrade
`protean ir check` flagged every domain as stale while `protean ir diff` reported "no changes"; regenerating showed only volatile metadata had moved. `_compute_checksum` hashed `ir_version` (and `$schema`/`elements`), so a framework-version-only bump changed the checksum. The checksum now excludes the **same** volatile/derived keys `diff_ir` ignores (`$schema`, `ir_version`, `generated_at`, `elements`), via a shared `_CHECKSUM_EXCLUDED_KEYS` constant, so the two commands stay in lockstep.

> Caveat: baselines materialized before this fix report stale **once** — regenerate with `protean ir show`.

## #1011 — `assert_valid`/`assert_invalid` removed with no deprecation cycle
They were dropped from `protean.testing` in 0.16.0, breaking downstream suites at import time (25 call sites in the reporter's app). That violates the breaking-change policy (ADR-0004: public helpers survive ≥2 minor versions behind a `DeprecationWarning`). Restored with faithful behavior; they now emit `DeprecationWarning` with removal in **v0.18.0**. Preferred replacement: `pytest.raises(ValidationError, match=...)`.

## Not in this PR
**#1010** (CLI logs corrupting stdout) is already on `main` (`65ea4470`). The 0.16.1 release will cherry-pick `65ea4470` + the two commits here onto `release/0.16.x`.

## Tests
- New `tests/testing/test_invariant_helpers.py` (behavior + deprecation contract) and a `TestChecksum` regression for #1012.
- `tests/ir` + `tests/testing`: 1301 passed. `ruff check` / `ruff format --check` clean.

Closes #1011
Closes #1012

### CODE REVIEW

File: src/protean/ir/builder.py [hunk 1]
```diff
@@ -36,6 +36,17 @@
     from protean.domain import Domain
 
 
+# Keys excluded from the content checksum: volatile metadata (the generation
+# timestamp and the checksum field itself) plus version/format markers that
+# change on a framework upgrade without the domain having changed. This set
+# MUST match the keys that ``protean.ir.diff.diff_ir`` ignores, so that
+# ``ir check`` (staleness) and ``ir diff`` agree — a framework-version-only
+# difference must not read as a domain change. See #1012.
```
[the remark this answers is not in the document]
Comment (subhashb) [reply src/protean/ir/builder.py]: Done in 6d96b842. Moved the set to a shared `src/protean/ir/constants.py` (`VOLATILE_IR_KEYS`); `builder._compute_checksum` imports it, and `diff_ir` references it in its docstring. `diff_ir` is positional (it diffs named content sections and has no key-based skip list), so rather than a dead import I enforced the lockstep *by code* with a new test that imports the shared constant and asserts `diff_ir(...)["summary"]["has_changes"] is False` **and** equal `_compute_checksum` for a version-only difference. Drift now fails that test.

File: tests/ir/test_ir_builder.py [hunk 2]
```diff
@@ -133,6 +133,26 @@ def test_checksum_changes_with_content(self):
...
+        domain = Domain(name="Volatile")
+        domain.init(traverse=False)
+        ir = domain.to_ir()
+
+        bumped = dict(ir)
+        bumped["ir_version"] = "9.9.9"
+        bumped["$schema"] = "https://protean.dev/ir/v9.9.9/schema.json"
+        bumped["generated_at"] = "2099-01-01T00:00:00Z"
+
+        assert IRBuilder._compute_checksum(bumped) == IRBuilder._compute_checksum(ir)
```
[the remark this answers is not in the document]
Comment (subhashb) [reply tests/ir/test_ir_builder.py:187]: Fixed in 6d96b842. The regression test now drives the full set from `VOLATILE_IR_KEYS` — it mutates every excluded key (`$schema`, `ir_version`, `generated_at`, `checksum`, `elements`) and asserts the checksum is unchanged for each, with `assert set(sentinels) == set(VOLATILE_IR_KEYS)` so it fails if the set grows and a sentinel is missing.

**Comment by subhashb** [comment]
Auto-backport hit an import-context conflict (the squash was computed on \`main\`, which has the #1007 imports-to-module-top refactor that \`release/0.16.x\` does not). Backported manually as \`16348b4f\` on \`release/0.16.x\`, resolving the conflict to add only the genuinely-new symbols (\`VOLATILE_IR_KEYS\`, \`ValidationError\`) without dragging main's module-top imports onto the maintenance branch. `tests/ir` + `tests/testing`: 1302 passed.
